### ISSUE TITLE
国内下载镜像忒慢,方便搞个国内镜像么?

### ISSUE THREAD

**Issue by gaojice** [frostynova/open-falcon-docker#1]
as title

**Comment by frostynova** [comment]
可以用 local 分支自己 Build 一个

**Comment by qzn928** [comment]
怎么biild啊，对docker不熟悉，能给个详细一点的步骤么？

**Comment by wiwengweng** [comment]
docker里面装的是server端吧？agent也要自己build吗？

**Comment by frostynova** [comment]
@wiwengweng 是的，agent 他们有做好的直接下载即可，自己 build 也行。

建议不要再使用这个仓库了，已经离现在的最新版差很远了
